package app54;

public class M36 {
	public static void main(String[] args) {
		try {
			
		}
		finally {
			
		}
		System.out.println("done");
	}
}
//it is possible b/c the finally is a last statement
//and try is also not alone
//catch is not here b/c exception is not here
//in this we ensure the some mandatory statement in the flow